version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

formats: []  # only build HTML

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
